sonar.projectKey=erp-project
sonar.projectName=ERP Project
sonar.projectVersion=33
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.language=py
sonar.exclusions=**/__pycache__/**,**/migrations/**,**/*.pyc,**/venv/**