# Unique Project ID
sonar.projectKey=shivsoftapp-devops-sonarqube-image

# Project Name
sonar.projectName=ShivSoftApp DevOps SonarQube Pipeline

# Project Version
sonar.projectVersion=33

# Scan entire workspace (IMPORTANT FIX)
sonar.sources=.

# Encoding
sonar.sourceEncoding=UTF-8

# Python project
sonar.language=py

# Exclusions
sonar.exclusions=**/__pycache__/**,**/migrations/**,**/venv/**,**/*.pyc