apiVersion: v1
kind: Service

metadata:
  name: devops-sonarqube-service

spec:
  type: NodePort

  selector:
    app: devops-sonarqube

  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30007