apiVersion: v1
kind: Service

metadata:
  name: devops-sonarqube-service

spec:
  type: NodePort

  selector:
    app: devops-sonarqube-app

  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007