apiVersion: v1
kind: Service

metadata:
name: erp-service
labels:
app: erp-app

spec:
type: NodePort

selector:
app: erp-app

ports:

  name: http
  port: 8000
  targetPort: 8000
  nodePort: 30007
